# Generated by Django 4.2.5 on 2023-09-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0010_loantransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('reject', 'Reject'), ('accept', 'Accepted')], default='pending', max_length=10, null=True),
        ),
    ]
