# Generated by Django 4.2.5 on 2023-09-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_alter_loanrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanParcent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_parc', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loanParcent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_parcent', to='loanApp.loanparcent'),
        ),
    ]
